services:

  fastapi:
    build:
      context: ./server/fastapi
      dockerfile: Dockerfile
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", '--reload' ]
    env_file:
      - ./server/fastapi/.env
    ports:
      - "8000:8000"
    volumes:
      - ./server/fastapi:/app

  prototype:
    build:
      context: ./clients/prototype
      dockerfile: Dockerfile
    ports:
      - "80:80"
